// <auto-generated />
namespace BandoApp.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuitarRegionesYDocumentos_AniadirAplicacionesAmigas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuitarRegionesYDocumentos_AniadirAplicacionesAmigas));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150857462_QuitarRegionesYDocumentos_AniadirAplicacionesAmigas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
