// <auto-generated />
namespace PushNews.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NuevosCampos_CorreccionesRelacionesYLimitesNVARCHAR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuevosCampos_CorreccionesRelacionesYLimitesNVARCHAR));
        
        string IMigrationMetadata.Id
        {
            get { return "201601141146425_NuevosCampos_CorreccionesRelacionesYLimitesNVARCHAR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
