// <auto-generated />
namespace PushNews.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EstadisticasPorAsociado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstadisticasPorAsociado));
        
        string IMigrationMetadata.Id
        {
            get { return "201702271709498_EstadisticasPorAsociado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
