// <auto-generated />
namespace PushNews.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmpresasActivo_RutasCorreccionLatitud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpresasActivo_RutasCorreccionLatitud));
        
        string IMigrationMetadata.Id
        {
            get { return "201702140918280_Empresas.Activo_Rutas.CorreccionLatitud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
