// <auto-generated />
namespace PushNews.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Gpss_Campo_Api : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gpss_Campo_Api));
        
        string IMigrationMetadata.Id
        {
            get { return "201903141618039_Gpss_Campo_Api"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
