// <auto-generated />
namespace PushNews.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CambiarITunesPorAppStore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiarITunesPorAppStore));
        
        string IMigrationMetadata.Id
        {
            get { return "202010170610545_CambiarITunesPorAppStore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
