//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aplicaciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aplicaciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Aplicaciones", typeof(Aplicaciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave de la API.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación.
        /// </summary>
        public static string Aplicacion {
            get {
                return ResourceManager.GetString("Aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La nueva aplicación de trabajo es {0}. Espere a que la página se recargue..
        /// </summary>
        public static string AplicacionCambiada {
            get {
                return ResourceManager.GetString("AplicacionCambiada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url de la app en la AppStore.
        /// </summary>
        public static string AppStoreUrl {
            get {
                return ResourceManager.GetString("AppStoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la aplicación.
        /// </summary>
        public static string ArtEntidad {
            get {
                return ResourceManager.GetString("ArtEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar aplicaciones....
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cambiar la aplicación.
        /// </summary>
        public static string CambiarAplicacionError {
            get {
                return ResourceManager.GetString("CambiarAplicacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación cambiada.
        /// </summary>
        public static string CambiarAplicacionExito {
            get {
                return ResourceManager.GetString("CambiarAplicacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Características.
        /// </summary>
        public static string Caracteristicas {
            get {
                return ResourceManager.GetString("Caracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione características de la aplicación.
        /// </summary>
        public static string CaracteristicasPlaceholder {
            get {
                return ResourceManager.GetString("CaracteristicasPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        public static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave actual.
        /// </summary>
        public static string ClaveActual {
            get {
                return ResourceManager.GetString("ClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave nueva.
        /// </summary>
        public static string ClaveNueva {
            get {
                return ResourceManager.GetString("ClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clonar aplicación.
        /// </summary>
        public static string Clonar {
            get {
                return ResourceManager.GetString("Clonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CloudKey.
        /// </summary>
        public static string CloudKey {
            get {
                return ResourceManager.GetString("CloudKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a activar la aplicación.
        /// </summary>
        public static string ConfirmacionActivar {
            get {
                return ResourceManager.GetString("ConfirmacionActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a desactivar la aplicación.
        /// </summary>
        public static string ConfirmacionDesactivar {
            get {
                return ResourceManager.GetString("ConfirmacionDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logotipo.
        /// </summary>
        public static string Logotipo {
            get {
                return ResourceManager.GetString("Logotipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación solicitada no existe o no está asignada al usuario actual..
        /// </summary>
        public static string NoExisteNoAsignada {
            get {
                return ResourceManager.GetString("NoExisteNoAsignada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de aplicación.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url de la app en Play Store.
        /// </summary>
        public static string PlayStoreUrl {
            get {
                return ResourceManager.GetString("PlayStoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicaciones móviles.
        /// </summary>
        public static string SeccionAplicacionesMoviles {
            get {
                return ResourceManager.GetString("SeccionAplicacionesMoviles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claves de API Push.
        /// </summary>
        public static string SeccionClavesAPIPush {
            get {
                return ResourceManager.GetString("SeccionClavesAPIPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string SeccionIdentificacion {
            get {
                return ResourceManager.GetString("SeccionIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros datos.
        /// </summary>
        public static string SeccionOtrosDatos {
            get {
                return ResourceManager.GetString("SeccionOtrosDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdominio.
        /// </summary>
        public static string SubDominio {
            get {
                return ResourceManager.GetString("SubDominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de aplicaciones.
        /// </summary>
        public static string Subtitulo {
            get {
                return ResourceManager.GetString("Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
