//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Categorias {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categorias() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Categorias", typeof(Categorias).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la categoría.
        /// </summary>
        public static string ArtEntidad {
            get {
                return ResourceManager.GetString("ArtEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar categorías.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a activar la categoría.
        /// </summary>
        public static string ConfirmacionActivar {
            get {
                return ResourceManager.GetString("ConfirmacionActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a desactivar la categoría.
        /// </summary>
        public static string ConfirmacionDesactivar {
            get {
                return ResourceManager.GetString("ConfirmacionDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a eliminar la categoría.
        /// </summary>
        public static string ConfirmacionEliminar {
            get {
                return ResourceManager.GetString("ConfirmacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icono.
        /// </summary>
        public static string Icono {
            get {
                return ResourceManager.GetString("Icono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación no autorizada.
        /// </summary>
        public static string NoPermitido {
            get {
                return ResourceManager.GetString("NoPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string Orden {
            get {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de categorías.
        /// </summary>
        public static string Subtitulo {
            get {
                return ResourceManager.GetString("Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
