//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Comunicaciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Comunicaciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Comunicaciones", typeof(Comunicaciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos.
        /// </summary>
        public static string Accesos {
            get {
                return ResourceManager.GetString("Accesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo adjunto.
        /// </summary>
        public static string Adjunto {
            get {
                return ResourceManager.GetString("Adjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título del adjunto.
        /// </summary>
        public static string AdjuntoTitulo {
            get {
                return ResourceManager.GetString("AdjuntoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la comunicación.
        /// </summary>
        public static string ArtEntidad {
            get {
                return ResourceManager.GetString("ArtEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autor.
        /// </summary>
        public static string Autor {
            get {
                return ResourceManager.GetString("Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrada.
        /// </summary>
        public static string Borrado {
            get {
                return ResourceManager.GetString("Borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar comunicaciones....
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El módulo coordenadas requiere que el contenedor contenga un div con la clase &apos;mapa-entrada&apos;..
        /// </summary>
        public static string CapaMapaNoEncontrada {
            get {
                return ResourceManager.GetString("CapaMapaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No está autorizado para utilizar la categoría seleccionada..
        /// </summary>
        public static string CategoriaNoPermitida {
            get {
                return ResourceManager.GetString("CategoriaNoPermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicación.
        /// </summary>
        public static string Comunicacion {
            get {
                return ResourceManager.GetString("Comunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación se ha guardado..
        /// </summary>
        public static string ComunicacionGuardada {
            get {
                return ResourceManager.GetString("ComunicacionGuardada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a activar la comunicación.
        /// </summary>
        public static string ConfirmacionActivar {
            get {
                return ResourceManager.GetString("ConfirmacionActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a desactivar la comunicación.
        /// </summary>
        public static string ConfirmacionDesactivar {
            get {
                return ResourceManager.GetString("ConfirmacionDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a eliminar la comunicación.
        /// </summary>
        public static string ConfirmacionEliminar {
            get {
                return ResourceManager.GetString("ConfirmacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el contenedor..
        /// </summary>
        public static string ContenedorNoEncontrado {
            get {
                return ResourceManager.GetString("ContenedorNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacada.
        /// </summary>
        public static string Destacado {
            get {
                return ResourceManager.GetString("Destacado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destacadas.
        /// </summary>
        public static string Destacados {
            get {
                return ResourceManager.GetString("Destacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace.
        /// </summary>
        public static string Enlace {
            get {
                return ResourceManager.GetString("Enlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título del enlace.
        /// </summary>
        public static string EnlaceTitulo {
            get {
                return ResourceManager.GetString("EnlaceTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo cargar la comunicación solicitada.
        /// </summary>
        public static string ErrorCargarNotificacion {
            get {
                return ResourceManager.GetString("ErrorCargarNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede editar una comunicación publicada..
        /// </summary>
        public static string ErrorEditarComunicacionPublicada {
            get {
                return ResourceManager.GetString("ErrorEditarComunicacionPublicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al calcular la dirección asociada a las coordenadas..
        /// </summary>
        public static string ErrorGeocoding {
            get {
                return ResourceManager.GetString("ErrorGeocoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallo al calcular las coordenadas asociadas a la dirección..
        /// </summary>
        public static string ErrorGeocodingInverso {
            get {
                return ResourceManager.GetString("ErrorGeocodingInverso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el archivo.
        /// </summary>
        public static string ErrorSubirFichero {
            get {
                return ResourceManager.GetString("ErrorSubirFichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de publicación.
        /// </summary>
        public static string EstadoPublicacion {
            get {
                return ResourceManager.GetString("EstadoPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creación.
        /// </summary>
        public static string FechaCreacion {
            get {
                return ResourceManager.GetString("FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de publicación.
        /// </summary>
        public static string FechaPublicacion {
            get {
                return ResourceManager.GetString("FechaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar comunicaciones.
        /// </summary>
        public static string FiltroDestacadasMensaje {
            get {
                return ResourceManager.GetString("FiltroDestacadasMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado unas coordenadas asociadas a la dirección..
        /// </summary>
        public static string GeocodingInversoSinResultado {
            get {
                return ResourceManager.GetString("GeocodingInversoSinResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado una dirección para las coordenadas..
        /// </summary>
        public static string GeocodingSinResultado {
            get {
                return ResourceManager.GetString("GeocodingSinResultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        public static string GeoPosicionLatitud {
            get {
                return ResourceManager.GetString("GeoPosicionLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string GeoPosicionLongitud {
            get {
                return ResourceManager.GetString("GeoPosicionLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título de la ubicación.
        /// </summary>
        public static string GeoPosicionTitulo {
            get {
                return ResourceManager.GetString("GeoPosicionTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título de la imagen.
        /// </summary>
        public static string ImagenTitulo {
            get {
                return ResourceManager.GetString("ImagenTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene autorización para crear o editar comunicaciones de la categoría {0}..
        /// </summary>
        public static string ModificacionDenegadaPorCategoria {
            get {
                return ResourceManager.GetString("ModificacionDenegadaPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No destacadas.
        /// </summary>
        public static string NoDestacados {
            get {
                return ResourceManager.GetString("NoDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener coordenadas.
        /// </summary>
        public static string ObtenerCoordenadas {
            get {
                return ResourceManager.GetString("ObtenerCoordenadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener las coordenadas correspondientes a la dirección introducida..
        /// </summary>
        public static string ObtenerCoordenadasTitle {
            get {
                return ResourceManager.GetString("ObtenerCoordenadasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener dirección.
        /// </summary>
        public static string ObtenerDireccion {
            get {
                return ResourceManager.GetString("ObtenerDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obtener la dirección correspondiente a las coordenadas introducidas..
        /// </summary>
        public static string ObtenerDireccionTitle {
            get {
                return ResourceManager.GetString("ObtenerDireccionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificación push.
        /// </summary>
        public static string PushFecha {
            get {
                return ResourceManager.GetString("PushFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar adjunto.
        /// </summary>
        public static string QuitarAdjunto {
            get {
                return ResourceManager.GetString("QuitarAdjunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar imagen.
        /// </summary>
        public static string QuitarImagen {
            get {
                return ResourceManager.GetString("QuitarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio.
        /// </summary>
        public static string Recordatorio {
            get {
                return ResourceManager.GetString("Recordatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de recordatorio.
        /// </summary>
        public static string RecordatorioFecha {
            get {
                return ResourceManager.GetString("RecordatorioFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título de recordatorio.
        /// </summary>
        public static string RecordatorioTitulo {
            get {
                return ResourceManager.GetString("RecordatorioTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una categoría.
        /// </summary>
        public static string SeleccioneCategoria {
            get {
                return ResourceManager.GetString("SeleccioneCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de comunicaciones.
        /// </summary>
        public static string Subtitulo {
            get {
                return ResourceManager.GetString("Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de geocoding.
        /// </summary>
        public static string TituloErrorGeocoding {
            get {
                return ResourceManager.GetString("TituloErrorGeocoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas.
        /// </summary>
        public static string TodasLasComunicaciones {
            get {
                return ResourceManager.GetString("TodasLasComunicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totales.
        /// </summary>
        public static string Totales {
            get {
                return ResourceManager.GetString("Totales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP de la última edición.
        /// </summary>
        public static string UltimaEdicionIP {
            get {
                return ResourceManager.GetString("UltimaEdicionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Último mes.
        /// </summary>
        public static string UltimoMes {
            get {
                return ResourceManager.GetString("UltimoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizaciones.
        /// </summary>
        public static string Visualizaciones {
            get {
                return ResourceManager.GetString("Visualizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VisualizacionesTotales.
        /// </summary>
        public static string VisualizacionesTotales {
            get {
                return ResourceManager.GetString("VisualizacionesTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizaciones del último mes.
        /// </summary>
        public static string VisualizacionesUltimoMes {
            get {
                return ResourceManager.GetString("VisualizacionesUltimoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video de Youtube.
        /// </summary>
        public static string Youtube {
            get {
                return ResourceManager.GetString("Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título del video de Youtube.
        /// </summary>
        public static string YoutubeTitulo {
            get {
                return ResourceManager.GetString("YoutubeTitulo", resourceCulture);
            }
        }
    }
}
