//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Listas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Listas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Listas", typeof(Listas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar vídeo.
        /// </summary>
        public static string AplicacionCaracteristicaAdjuntarVideo {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaAdjuntarVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntos múltiples.
        /// </summary>
        public static string AplicacionCaracteristicaAdjuntosMultiples {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaAdjuntosMultiples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociados.
        /// </summary>
        public static string AplicacionCaracteristicaAsociados {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directorio comercial.
        /// </summary>
        public static string AplicacionCaracteristicaDirectorioComercial {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaDirectorioComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas.
        /// </summary>
        public static string AplicacionCaracteristicaEmpresas {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar coordenadas.
        /// </summary>
        public static string AplicacionCaracteristicaGeoPosicionamiento {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaGeoPosicionamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermandades.
        /// </summary>
        public static string AplicacionCaracteristicaHermandades {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaHermandades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imágenes múltiples.
        /// </summary>
        public static string AplicacionCaracteristicaImagenesMultiples {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaImagenesMultiples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronización con Facebook.
        /// </summary>
        public static string AplicacionCaracteristicaSincronizacionFacebook {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaSincronizacionFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronización con Twitter.
        /// </summary>
        public static string AplicacionCaracteristicaSincronizacionTwitter {
            get {
                return ResourceManager.GetString("AplicacionCaracteristicaSincronizacionTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención.
        /// </summary>
        public static string EstadosPublicacionAtencion {
            get {
                return ResourceManager.GetString("EstadosPublicacionAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación o el recordatorio no ha podido enviarse..
        /// </summary>
        public static string EstadosPublicacionAtencionTitle {
            get {
                return ResourceManager.GetString("EstadosPublicacionAtencionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caducado.
        /// </summary>
        public static string EstadosPublicacionCaducado {
            get {
                return ResourceManager.GetString("EstadosPublicacionCaducado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación no será enviada debido a la fecha de publicación, si desea enviar la comunicación cree una nueva o actualice la fecha de publicación..
        /// </summary>
        public static string EstadosPublicacionCaducadoTitle {
            get {
                return ResourceManager.GetString("EstadosPublicacionCaducadoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviado.
        /// </summary>
        public static string EstadosPublicacionEnviado {
            get {
                return ResourceManager.GetString("EstadosPublicacionEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación ha sido enviada satisfactoriamente..
        /// </summary>
        public static string EstadosPublicacionEnviadoTitle {
            get {
                return ResourceManager.GetString("EstadosPublicacionEnviadoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planificado.
        /// </summary>
        public static string EstadosPublicacionPlanificado {
            get {
                return ResourceManager.GetString("EstadosPublicacionPlanificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La comunicación se enviará próximamente..
        /// </summary>
        public static string EstadosPublicacionPlanificadoTitle {
            get {
                return ResourceManager.GetString("EstadosPublicacionPlanificadoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio.
        /// </summary>
        public static string EstadosPublicacionRecordar {
            get {
                return ResourceManager.GetString("EstadosPublicacionRecordar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente de enviar un recordatorio de la comunicación..
        /// </summary>
        public static string EstadosPublicacionRecordarTitle {
            get {
                return ResourceManager.GetString("EstadosPublicacionRecordarTitle", resourceCulture);
            }
        }
    }
}
