//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Rutas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rutas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Rutas", typeof(Rutas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la ruta.
        /// </summary>
        public static string ArtEntidad {
            get {
                return ResourceManager.GetString("ArtEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar rutas.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación de la cabeza.
        /// </summary>
        public static string CabezaUltimaPosicionDireccion {
            get {
                return ResourceManager.GetString("CabezaUltimaPosicionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de datos de cabeza.
        /// </summary>
        public static string CabezaUltimaPosicionFecha {
            get {
                return ResourceManager.GetString("CabezaUltimaPosicionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de la cabeza (latitud).
        /// </summary>
        public static string CabezaUltimaPosicionLatitud {
            get {
                return ResourceManager.GetString("CabezaUltimaPosicionLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de la cabeza (longitud).
        /// </summary>
        public static string CabezaUltimaPosicionLongitud {
            get {
                return ResourceManager.GetString("CabezaUltimaPosicionLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia total recorrida (km).
        /// </summary>
        public static string CalculoDistancia {
            get {
                return ResourceManager.GetString("CalculoDistancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo transcurrido.
        /// </summary>
        public static string CalculoTiempo {
            get {
                return ResourceManager.GetString("CalculoTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad media (m/h).
        /// </summary>
        public static string CalculoVelocidad {
            get {
                return ResourceManager.GetString("CalculoVelocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera oficial.
        /// </summary>
        public static string CarreraOficial {
            get {
                return ResourceManager.GetString("CarreraOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación de la cola.
        /// </summary>
        public static string ColaUltimaPosicionDireccion {
            get {
                return ResourceManager.GetString("ColaUltimaPosicionDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de datos de cola.
        /// </summary>
        public static string ColaUltimaPosicionFecha {
            get {
                return ResourceManager.GetString("ColaUltimaPosicionFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de la cola (latitud).
        /// </summary>
        public static string ColaUltimaPosicionLatitud {
            get {
                return ResourceManager.GetString("ColaUltimaPosicionLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de la cola (longitud).
        /// </summary>
        public static string ColaUltimaPosicionLongitud {
            get {
                return ResourceManager.GetString("ColaUltimaPosicionLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a eliminar la ruta.
        /// </summary>
        public static string ConfirmacionEliminar {
            get {
                return ResourceManager.GetString("ConfirmacionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cruz de guía.
        /// </summary>
        public static string CruzDeGuia {
            get {
                return ResourceManager.GetString("CruzDeGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia recorrida.
        /// </summary>
        public static string DistanciaRecorrida {
            get {
                return ResourceManager.GetString("DistanciaRecorrida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo de Ramos.
        /// </summary>
        public static string DomingoRamos {
            get {
                return ResourceManager.GetString("DomingoRamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingo de Resurrección.
        /// </summary>
        public static string DomingoResurreccion {
            get {
                return ResourceManager.GetString("DomingoResurreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada en carrera oficial.
        /// </summary>
        public static string EntradaEnCarreraOficial {
            get {
                return ResourceManager.GetString("EntradaEnCarreraOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de entrada en carrera oficial (latitud).
        /// </summary>
        public static string EntradaEnCarreraOficialLatitud {
            get {
                return ResourceManager.GetString("EntradaEnCarreraOficialLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de entrada en carrera oficial (longitud).
        /// </summary>
        public static string EntradaEnCarreraOficialLongitud {
            get {
                return ResourceManager.GetString("EntradaEnCarreraOficialLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la capa de mapa. Para que el script funcione requiere un div con id &quot;mapa&quot;..
        /// </summary>
        public static string ErrorCapaMapaNoEncontrada {
            get {
                return ResourceManager.GetString("ErrorCapaMapaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar hermandades.
        /// </summary>
        public static string FiltroTitulo {
            get {
                return ResourceManager.GetString("FiltroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de la carrera oficial.
        /// </summary>
        public static string FinCarreraOficial {
            get {
                return ResourceManager.GetString("FinCarreraOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de cortejo.
        /// </summary>
        public static string FinDeCortejo {
            get {
                return ResourceManager.GetString("FinDeCortejo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de fin.
        /// </summary>
        public static string FinDescripcion {
            get {
                return ResourceManager.GetString("FinDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de fin.
        /// </summary>
        public static string FinFecha {
            get {
                return ResourceManager.GetString("FinFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de fin (latitud).
        /// </summary>
        public static string FinLatitud {
            get {
                return ResourceManager.GetString("FinLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de fin (longitud).
        /// </summary>
        public static string FinLongitud {
            get {
                return ResourceManager.GetString("FinLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS de cabeza.
        /// </summary>
        public static string GpsCabeza {
            get {
                return ResourceManager.GetString("GpsCabeza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ApiID del gps de cabeza.
        /// </summary>
        public static string GpsCabezaApiID {
            get {
                return ResourceManager.GetString("GpsCabezaApiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula del gps de cabeza.
        /// </summary>
        public static string GpsCabezaMatricula {
            get {
                return ResourceManager.GetString("GpsCabezaMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS de cola.
        /// </summary>
        public static string GpsCola {
            get {
                return ResourceManager.GetString("GpsCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ApiID del gps de cola.
        /// </summary>
        public static string GpsColaApiID {
            get {
                return ResourceManager.GetString("GpsColaApiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula del gps de cola.
        /// </summary>
        public static string GpsColaMatricula {
            get {
                return ResourceManager.GetString("GpsColaMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermandad.
        /// </summary>
        public static string Hermandad {
            get {
                return ResourceManager.GetString("Hermandad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas las hermandades.
        /// </summary>
        public static string HermandadesTodas {
            get {
                return ResourceManager.GetString("HermandadesTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string IglesiaDireccion {
            get {
                return ResourceManager.GetString("IglesiaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iglesia.
        /// </summary>
        public static string IglesiaNombre {
            get {
                return ResourceManager.GetString("IglesiaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de la carrera oficial.
        /// </summary>
        public static string InicioCarreraOficial {
            get {
                return ResourceManager.GetString("InicioCarreraOficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de inicio.
        /// </summary>
        public static string InicioDescripcion {
            get {
                return ResourceManager.GetString("InicioDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de inicio.
        /// </summary>
        public static string InicioFecha {
            get {
                return ResourceManager.GetString("InicioFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de inicio (latitud).
        /// </summary>
        public static string InicioLatitud {
            get {
                return ResourceManager.GetString("InicioLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas de inicio (longitud).
        /// </summary>
        public static string InicioLongitud {
            get {
                return ResourceManager.GetString("InicioLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jueves Santo.
        /// </summary>
        public static string JuevesSanto {
            get {
                return ResourceManager.GetString("JuevesSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lunes Santo.
        /// </summary>
        public static string LunesSanto {
            get {
                return ResourceManager.GetString("LunesSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martes Santo.
        /// </summary>
        public static string MartesSanto {
            get {
                return ResourceManager.GetString("MartesSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miércoles Santo.
        /// </summary>
        public static string MiercolesSanto {
            get {
                return ResourceManager.GetString("MiercolesSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string PatrocinadorDireccion {
            get {
                return ResourceManager.GetString("PatrocinadorDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facebook.
        /// </summary>
        public static string PatrocinadorFacebook {
            get {
                return ResourceManager.GetString("PatrocinadorFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string PatrocinadorTelefono {
            get {
                return ResourceManager.GetString("PatrocinadorTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Twitter.
        /// </summary>
        public static string PatrocinadorTwitter {
            get {
                return ResourceManager.GetString("PatrocinadorTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web.
        /// </summary>
        public static string PatrocinadorWeb {
            get {
                return ResourceManager.GetString("PatrocinadorWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin de cortejo.
        /// </summary>
        public static string PosicionCola {
            get {
                return ResourceManager.GetString("PosicionCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cruz de guía.
        /// </summary>
        public static string PosicionCruzGuia {
            get {
                return ResourceManager.GetString("PosicionCruzGuia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sábado Santo.
        /// </summary>
        public static string SabadoSanto {
            get {
                return ResourceManager.GetString("SabadoSanto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida.
        /// </summary>
        public static string Salida {
            get {
                return ResourceManager.GetString("Salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string SeccionIdentificacion {
            get {
                return ResourceManager.GetString("SeccionIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recorrido.
        /// </summary>
        public static string SeccionRecorrido {
            get {
                return ResourceManager.GetString("SeccionRecorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string SeleccioneGPSCola {
            get {
                return ResourceManager.GetString("SeleccioneGPSCola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de rutas.
        /// </summary>
        public static string Subtitulo {
            get {
                return ResourceManager.GetString("Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad media.
        /// </summary>
        public static string VelocidadMedia {
            get {
                return ResourceManager.GetString("VelocidadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viernes Santo.
        /// </summary>
        public static string ViernesSanto {
            get {
                return ResourceManager.GetString("ViernesSanto", resourceCulture);
            }
        }
    }
}
