//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNews.WebApp.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Secciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Secciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PushNews.WebApp.App_LocalResources.Secciones", typeof(Secciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        public static string Administracion {
            get {
                return ResourceManager.GetString("Administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicaciones.
        /// </summary>
        public static string Aplicaciones {
            get {
                return ResourceManager.GetString("Aplicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Características de aplicaciones.
        /// </summary>
        public static string AplicacionesCaracteristicas {
            get {
                return ResourceManager.GetString("AplicacionesCaracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociados.
        /// </summary>
        public static string Asociados {
            get {
                return ResourceManager.GetString("Asociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorías.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicaciones.
        /// </summary>
        public static string Comunicaciones {
            get {
                return ResourceManager.GetString("Comunicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string Configuracion {
            get {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresas.
        /// </summary>
        public static string Empresas {
            get {
                return ResourceManager.GetString("Empresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escritorio.
        /// </summary>
        public static string Escritorio {
            get {
                return ResourceManager.GetString("Escritorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPSs.
        /// </summary>
        public static string Gpss {
            get {
                return ResourceManager.GetString("Gpss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermandades.
        /// </summary>
        public static string Hermandades {
            get {
                return ResourceManager.GetString("Hermandades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localizaciones.
        /// </summary>
        public static string Localizaciones {
            get {
                return ResourceManager.GetString("Localizaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Opciones {
            get {
                return ResourceManager.GetString("Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros.
        /// </summary>
        public static string Parametros {
            get {
                return ResourceManager.GetString("Parametros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfiles.
        /// </summary>
        public static string Perfiles {
            get {
                return ResourceManager.GetString("Perfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regiones.
        /// </summary>
        public static string Regiones {
            get {
                return ResourceManager.GetString("Regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rutas.
        /// </summary>
        public static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefonos de interés.
        /// </summary>
        public static string Telefonos {
            get {
                return ResourceManager.GetString("Telefonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
